### PR TITLE
Fix CIGAR size calculation for insertions

### LINKED ISSUE #109: Reinjected sequences on matches containing inserts are invalid according to samtools
The issue is captured in the test-case added in 1068e2943b5990c65e95daab2255c17574805f38.

It basically boils down to `samtools` considering `I` in CIGAR strings to add to the length of the sequence. As such a CIGAR `5M1I5M` is considered to have length `11` while current code calculates `10` due to ignoring `I` in:
https://github.com/ngless-toolkit/ngless/blob/1068e2943b5990c65e95daab2255c17574805f38/NGLess/Data/Sam.hs#L195

### PR DESCRIPTION
**Pull request by unode**
This fixes #109 but has potential implications in several code paths (calculation of % identity, which sequence is kept, ...) so requesting a review and further scrutiny before merge.

Tests will likely fail due to #110 .

### CODE REVIEW

**Comment by unode** [comment]
A small update:

On a local analysis 90 samples were failing due to CIGAR errors, the patch above fixed the problem for all of them without noticeable effects to other samples.

**Comment by luispedro** [comment]
This looks all good to me.

I am not sure about the backwards compatibility implications, though, and whether it needs to be have a check for versions.

**Comment by unode** [comment]
> I am not sure about the backwards compatibility implications, though, and whether it needs to be have a check for versions.

I can't really assess backwards compatibility either. I'm still surprised we never ran into this before. Wondering if there's a samtools strictness change in the latest version that is now causing these to fail.

I agree that versioning this change makes sense. Perhaps with a warning much like the one in `select()` for `0.8`. I'll look into it.

**Comment by unode** [comment]
Given this function isn't part of `NGLessIO` and is used in quite a few locations, most of them pure, what's your recommendation for implementing the warning and backwards compatibility behavior?

**Comment by luispedro** [comment]
I looked at this again: the reinjection can be a hard upgrade because the previous version was wrong. The tricky part is when this is used for computing match identities and sizes. I just threaded a boolean through the code. It's an inelegant solution, but it gets the job done.

**Comment by unode** [comment]
Cool, thanks for the fix!

**Pull request merged**
